package ModelCorrispondenceDefinitionLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptModelCorrispondence = createDescriptorForModelCorrispondence();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptModelCorrispondence);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ModelCorrispondence:
        return myConceptModelCorrispondence;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList();
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForModelCorrispondence() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("ModelCorrispondenceDefinitionLang", "ModelCorrispondence", 0x1f0bc51ec42e4fcfL, 0x9c75cd7541f3ced8L, 0x62bfe6ad77b3ce8dL);
    b.class_(false, false, true);
    b.origin("r:2b42a15e-5871-42ba-af47-f2e38a5a5c4e(ModelCorrispondenceDefinitionLang.structure)/7115659568980676237");
    b.version(2);
    b.associate("left", 0x62bfe6ad77b3ce90L).target(0x8bb65ad4dfaf4fcdL, 0x98f7a7c33f5b8ab8L, 0x551d94c4dedafL).optional(false).origin("7115659568980676240").done();
    b.associate("right", 0x62bfe6ad77b3ce8eL).target(0x8bb65ad4dfaf4fcdL, 0x98f7a7c33f5b8ab8L, 0x551d94c4dedafL).optional(false).origin("7115659568980676238").done();
    return b.create();
  }
}
