package DesignSpacePlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import jetbrains.mps.ide.actions.Tools_ActionGroup;

public class DesignSpacePlugin_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("DesignSpacePlugin");
  public DesignSpacePlugin_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new DoPushout_Action());
    // groups 
    addGroup(new DesignSpacePluginGroup_ActionGroup());
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(DesignSpacePluginGroup_ActionGroup.ID, Tools_ActionGroup.ID, null);
  }
}
