package DesignSpacePlugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class DesignSpacePluginGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "DesignSpacePlugin.plugin.DesignSpacePluginGroup_ActionGroup";
  public DesignSpacePluginGroup_ActionGroup() {
    super("DesignSpacePluginGroup", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    DesignSpacePluginGroup_ActionGroup.this.addAction("DesignSpacePlugin.plugin.DoPushout_Action");
  }
}
